base_path: /lang
preserve_hierarchy: true

files:
  # PHP language files - root level
  - source: /en/*.php
    translation: /%two_letters_code%_%two_letters_code_upper%/%original_file_name%

  # PHP language files - settings subdirectory
  - source: /en/settings/*.php
    translation: /%two_letters_code%_%two_letters_code_upper%/settings/%original_file_name%