<?php

namespace App\OpenApi\Schemas;

use OpenApi\Attributes as OA;

#[OA\Schema(
    schema: 'Result',
    type: 'object',
    description: 'Speedtest result entry',
    properties: [
        new OA\Property(property: 'id', type: 'integer'),
        new OA\Property(property: 'service', type: 'string'),
        new OA\Property(property: 'status', type: 'string'),
        new OA\Property(property: 'scheduled', type: 'boolean'),
        new OA\Property(property: 'healthy', type: 'boolean', nullable: true),
        new OA\Property(property: 'ping', type: 'number', format: 'float', nullable: true),
        new OA\Property(property: 'ping_jitter', type: 'number', format: 'float', nullable: true),
        new OA\Property(property: 'ping_low', type: 'number', format: 'float', nullable: true),
        new OA\Property(property: 'ping_high', type: 'number', format: 'float', nullable: true),
        new OA\Property(property: 'download', type: 'integer', nullable: true),
        new OA\Property(property: 'download_bits', type: 'integer', nullable: true),
        new OA\Property(property: 'download_bits_human', type: 'string', nullable: true),
        new OA\Property(property: 'download_bytes', type: 'integer', nullable: true),
        new OA\Property(property: 'download_bytes_human', type: 'string', nullable: true),
        new OA\Property(property: 'download_jitter', type: 'number', format: 'float', nullable: true),
        new OA\Property(property: 'download_latency_iqm', type: 'number', format: 'float', nullable: true),
        new OA\Property(property: 'download_latency_low', type: 'number', format: 'float', nullable: true),
        new OA\Property(property: 'download_latency_high', type: 'number', format: 'float', nullable: true),
        new OA\Property(property: 'download_elapsed', type: 'integer', nullable: true),
        new OA\Property(property: 'upload', type: 'integer', nullable: true),
        new OA\Property(property: 'upload_bits', type: 'integer', nullable: true),
        new OA\Property(property: 'upload_bits_human', type: 'string', nullable: true),
        new OA\Property(property: 'upload_bytes', type: 'integer', nullable: true),
        new OA\Property(property: 'upload_bytes_human', type: 'string', nullable: true),
        new OA\Property(property: 'upload_jitter', type: 'number', format: 'float', nullable: true),
        new OA\Property(property: 'upload_latency_iqm', type: 'number', format: 'float', nullable: true),
        new OA\Property(property: 'upload_latency_low', type: 'number', format: 'float', nullable: true),
        new OA\Property(property: 'upload_latency_high', type: 'number', format: 'float', nullable: true),
        new OA\Property(property: 'upload_elapsed', type: 'integer', nullable: true),
        new OA\Property(property: 'packet_loss', type: 'number', format: 'float', nullable: true),
        new OA\Property(property: 'isp', type: 'string', nullable: true),
        new OA\Property(property: 'ip_address', type: 'string', format: 'ipv4', nullable: true),
        new OA\Property(property: 'server_id', type: 'integer', nullable: true),
        new OA\Property(property: 'server_name', type: 'string', nullable: true),
        new OA\Property(property: 'server_host', type: 'string', nullable: true),
        new OA\Property(property: 'server_ip', type: 'string', format: 'ipv4', nullable: true),
        new OA\Property(property: 'server_country', type: 'string', nullable: true),
        new OA\Property(property: 'server_location', type: 'string', nullable: true),
        new OA\Property(property: 'result_url', type: 'string', format: 'uri', nullable: true),
        new OA\Property(property: 'error_message', type: 'string', nullable: true),
        new OA\Property(property: 'benchmarks', type: 'array', nullable: true, items: new OA\Items(type: 'object')),
        new OA\Property(property: 'dispatched_by', type: 'integer', nullable: true),
        new OA\Property(property: 'comments', type: 'string', nullable: true),
        new OA\Property(property: 'created_at', type: 'string', format: 'date-time'),
        new OA\Property(property: 'updated_at', type: 'string', format: 'date-time'),
    ],
    additionalProperties: false
)]
class ResultSchema {}
