#!/command/with-contenv bash

# Exit on error
set -e

echo ""
echo "🐇  Configuring Speedtest Tracker..."
echo ""

# Fix permissions
echo "🔒  Fixing app path file permissions..."
chmod -R 755 /config
chown -R webuser:webgroup /config
chmod -R 755 $WEBUSER_HOME/storage
chown -R webuser:webgroup $WEBUSER_HOME/storage
echo "✅  Done."
echo ""

if [ ${DB_CONNECTION:="sqlite"} = "sqlite" ]; then
    # create symlinks
    echo "🔗  Creating database symlink..."
    symlinks=( \
    /var/www/html/database/database.sqlite \
    )

    for i in "${symlinks[@]}"
    do
        if [[ -e "$i" && ! -L "$i" ]]; then
            rm -rf "$i"
        fi
        if [[ ! -L "$i" ]]; then
            ln -s /config/"$(basename "$i")" "$i"
        fi
    done

    echo "✅  Done."
    echo ""
fi

# Check for app key
if [ ! ${APP_KEY} ]; then
    echo "⚠️  An application key is missing!"
    echo "👀  To set an application key, read the docs: https://docs.speedtest-tracker.dev/"
fi

echo ""

# Refresh cache
echo "💰  Refreshing the cache..."
s6-setuidgid webuser php $WEBUSER_HOME/artisan config:cache --no-ansi -q
s6-setuidgid webuser php $WEBUSER_HOME/artisan route:cache --no-ansi -q
s6-setuidgid webuser php $WEBUSER_HOME/artisan view:clear --no-ansi -q
echo "✅  Done."
echo ""

# Migrate database
echo "🚛  Migrating the database..."
s6-setuidgid webuser php $WEBUSER_HOME/artisan migrate --force --no-ansi -q
echo "✅  Done."
echo ""

# App install done, show a message
echo "✅  All set, Speedtest Tracker has started!"
echo ""
