#!/command/with-contenv bash

# Exit on error
set -e

echo "🐇  Configuring Speedtest Tracker..."

if [ ${DB_CONNECTION:="sqlite"} == "sqlite" ]; then
    # Check for database
    if [ ! -f /config/database.sqlite ]; then
        echo "🙄  Database file not found, creating..."
        touch /config/database.sqlite
    else
        echo "✅  Database exists"
    fi

    # create symlinks
    echo "🔗  Creating database symlink"
    symlinks=( \
    /var/www/html/database/database.sqlite \
    )

    for i in "${symlinks[@]}"
    do
        if [[ -e "$i" && ! -L "$i" ]]; then
            rm -rf "$i"
        fi
        if [[ ! -L "$i" ]]; then
            ln -s /config/"$(basename "$i")" "$i"
        fi
    done
fi

# Check for env file
if [ ! -f /config/.env ]; then
    echo "🙄  Environment file not found, creating..."
    cp $WEBUSER_HOME/.env.example /config/.env
else
    echo "✅  Environment file exists"
fi

# create symlinks
echo "🔗  Creating symlinks to config and log files"
symlinks=( \
/var/www/html/.env \
/var/www/html/storage/logs/laravel.log
)

for i in "${symlinks[@]}"
do
    if [[ -e "$i" && ! -L "$i" ]]; then
        rm -rf "$i"
    fi
    if [[ ! -L "$i" ]]; then
        ln -s /config/"$(basename "$i")" "$i"
    fi
done

# Check for app key
if grep -E "APP_KEY=[0-9A-Za-z:+\/=]{1,}" $WEBUSER_HOME/.env > /dev/null; then
    echo "✅  App key exists"
else
    echo "⏳  Generating app key..."
    php $WEBUSER_HOME/artisan key:generate --no-ansi -q
fi

# Fix permissions
echo "🔒  Fixing app path file permissions"
chmod -R 755 /config
chown -R webuser:webgroup /config

# Build cache
echo "💰  Building the cache..."
s6-setuidgid webuser php $WEBUSER_HOME/artisan config:cache --no-ansi -q
s6-setuidgid webuser php $WEBUSER_HOME/artisan route:cache --no-ansi -q

# Migrate database
echo "🚛  Migrating the database..."
s6-setuidgid webuser php $WEBUSER_HOME/artisan migrate --force --no-ansi -q

# App install done, show a message
echo "✅  All set, starting Speedtest Tracker container..."

exit 0
