#!/usr/bin/with-contenv bash
# This needs to run before docker-php 50-laravel-automations
# so that everything is setup correctly.

# START FOR DEBUGGING ONLY
# echo "Working directory:" $(pwd)
# echo "Script running as user:" $(whoami)
# END FOR DEBIGGING ONLY

echo "🐇  Starting Speedtest Tracker..."

# Check for app data directory
if [ ! -d /app ]; then
    # make the directory
    echo "🙄  App data directory not found, creating..."

    su - webuser -c "mkdir /app"
    chown -R webuser:webgroup /app
    chmod -R 750 /app
else
    # just update the permissions
    echo "✅  App data directiory exists"

    chown -R webuser:webgroup /app
    chmod -R 750 /app
fi

if [ ${DB_CONNECTIONS:="sqlite"} == "sqlite" ]; then
    # Check for database
    if [ ! -f /app/database.sqlite ]; then
        echo "🙄  Database file not found, creating..."

        su - webuser -c "touch /app/database.sqlite"
        chmod 750 /app/database.sqlite
    else
        echo "✅  Database exists"
        chmod 750 /app/database.sqlite
    fi
fi

# Check for config yaml file
if [ ! -f /app/config.yml ]; then
    echo "🙄  Config file not found, creating..."

    su - webuser -c "cp /var/www/html/config.example.yml /app/config.yml"
    chmod 750 /app/config.yml
else
    echo "✅  Config file exists"
    chmod 750 /app/config.yml
fi

# Check for app key
if grep -E "APP_KEY=[0-9A-Za-z:+\/=]{1,}" /var/www/html/.env > /dev/null; then
    echo "✅  App key exists"
else
    echo "⏳  Generating app key"
    su - webuser -c "php $WEBUSER_HOME/artisan key:generate"
fi

# Link storage
echo "📦  Linking storage..."
su - webuser -c "php $WEBUSER_HOME/artisan storage:link"

echo "✅  All set, off to the races!"
