name: API Tests

on:
  push:
    branches:
      - '!main'
      - '!release-**'
    paths:
      - 'app/Http/Controllers/Api/**'
      - 'routes/api.php'
  pull_request:
    paths:
      - 'app/Http/Controllers/Api/**'
      - 'routes/api.php'
  workflow_dispatch:

jobs:
  test-api:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Create SQLite Database
        run: |
          touch database/testing.sqlite

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm ci && npm run build

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate App Key
        run: php artisan key:generate --quiet

      - name: Run API Tests
        run: php -d memory_limit=512M artisan test --parallel --testsuite=Api 