# .github/workflows/tests.yml
name: Tests

on:
  push:
    branches:
      - '!main'
      - '!release-**'
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Cache Composer dependencies
        uses: actions/cache@v5
        with:
          path: vendor
          key: composer-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-${{ runner.os }}-

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Run Pint
        run: vendor/bin/pint --test

  test:
    needs: lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Cache Composer dependencies
        uses: actions/cache@v5
        with:
          path: vendor
          key: composer-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-${{ runner.os }}-

      - name: Cache NPM dependencies
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

      - name: Create SQLite Database
        run: |
          touch database/database.sqlite

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --classmap-authoritative
          npm ci --no-audit && npm run build

      - name: Copy Environment File
        run: cp .env.ci .env

      - name: Generate App Key
        run: php artisan key:generate --quiet

      - name: Run Tests
        run: php artisan test
        env:
          DB_CONNECTION: sqlite
