name: 'Close stale issues'

on:
  schedule:
    - cron: '0 10 * * *'  # Runs daily at 10:00 AM UTC
  workflow_dispatch:

permissions:
  issues: write

jobs:
  manage-stale-issues:
    runs-on: ubuntu-24.04

    steps:
      - name: Close Stale Issues
        uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

          # Stale messaging
          stale-issue-message: >
            👋 This issue has been automatically marked as stale due to inactivity.
            If this issue is still relevant, please comment to keep it open.
            Without activity, it will be closed in 7 days.

          close-issue-message: >
            🔒 This issue has been automatically closed due to prolonged inactivity.
            Feel free to open a new issue if you have further questions or concerns.

          # Timing
          days-before-issue-stale: 14
          days-before-issue-close: 7

          # Label management
          stale-issue-label: 'stale'
          remove-stale-when-updated: true

          # Targeting only `question`-labeled issues
          only-issue-labels: 'question'
          exempt-issue-labels: >
            bug, chore, confirmed, dependencies, help wanted,
            documentation, duplicate, feature, good first issue,
            needs review, wontfix

          # Skip assigned or milestone-tracked issues
          exempt-assignees: true
          exempt-milestones: true
